### PR TITLE
added support for avif extension

### PR DESCRIPTION
**Pull request by alexfry**
added support for avif extension  https://en.wikipedia.org/wiki/AVIF

### CODE REVIEW

**Comment by jrowellfx** [comment]
Thanks Alex. I want to run this through all the regression tests, and possibly update the list of image types with any other newer extensions that might be worth adding now. Also need to publish a new release with this change, and add it to pypi. 

You know that you can use some env variables to add to the list of extensions that are considered to be images right?  Check out lsseq --help  and read the description up top that describes the env vars. Also try --imageExt optional arg.

**Comment by jrowellfx** [comment]
By the way, this ^^^ is all done now. New release with your changes, plus .heic and .heif extensions

**Comment by alexfry** [comment]
Ahh very cool!

I must have skim read the docs, I thought that flag was only dumping a list of the compatible extensions when I looked at it. 

Thanks for doing the update.

**Comment by jrowellfx** [comment]
You're welcome.

**Pull request merged**
